language: node_js
os:
  - linux
  - osx
  - windows
dist: focal
osx_image: xcode12.5
node_js:
  - 4.9.1
branches:
  only:
    - main
cache:
  directories:
    - node_modules
install:
  - npm set progress=false
  - npm install
script:
  - npm run prettier-check
  - npm run lint
  - npm run build
